export {
  type ProjectTemplate,
  type EndpointTemplate,
  textClassifierTemplate,
  sentimentAnalyzerTemplate,
  dataExtractorTemplate,
  contentGeneratorTemplate,
  localizationTemplate,
  imageRecognitionTemplate,
  imageGenerationTemplate,
  imageProcessingTemplate,
  audioTranscriptionTemplate,
  ALL_TEMPLATES,
  applyTemplate,
} from './endpoint-templates';
